labels:
  - name: 'Type: Issue (Expansion)'
    labeled:
      issue:
        body: |-
          Hello @{{ issue.user.login }},
          
          The issue you encountered is caused by an Expansion and not PlaceholderAPI itself.
          This issue-tracker is reserved for Bug reports and feature requests towards PlaceholderAPI.
          
          Please report this issue to the Expansion's main issue-tracker.
          
          > *This is an automated response created by a GitHub-Action.*
          > *Responding to the bot or mentioning it won't have any effect!*
  - name: 'Type: Duplicate'
    labeled:
      issue:
        body: |-
          Your issue is already known and a separate issue with the exact same report/feature request already exist.
          
          Please comment on the already existing issue with your information instead of opening your own.
          
          > *This is an automated response created by a GitHub-Action.*
          > *Responding to the bot or mentioning it won't have any effect!*
        action: close
  - name: 'Problem: More info required'
    labeled:
      issue:
        body: |-
          Hello @{{ issue.user.login }},
          
          Your issue unfortunately lacks certain information that we require in order to help you with your issue.
          Please make sure you provide the following information:
          
          - Currently used Versions of your server and PlaceholderAPI
          - Currently installed Expansions
          - Currently installed Plugins
          
          The easiest way to provide those information is through the `/papi dumb` command which posts the required information and gives a URL to share.
          
          > *This is an automated response created by a GitHub-Action.*
          > *Responding to the bot or mentioning it won't have any effect!*
    unlabeled:
      issue:
        body: |-
          Thank you for providing additional information.
          We will take a look at the issue you encounter and come back to you with a possible solution.
          
          > *This is an automated response created by a GitHub-Action. Responding to or mentioning this bot has no effect!*
  - name: 'Type: Invalid'
    labeled:
      issue:
        body: |-
          Your issue has beeen marked as invalid.
          This means that it either doesn't follow any provided template, or isn't related to PlaceholderAPI in any way.
          
          Please make sure to use one of the issue templates and provide the requested information.
          Currently available Templates are:
          
          - [Bug Report](https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md)
          - [Feature Request](https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=feature_request.md)
          
          If you want changes to be made towards the Wiki, would we encourage you to [Make a Pull request](https://github.com/PlaceholderAPI/PlaceholderAPI/pulls).  
          You can find more information about this process on the [Wiki's Readme](https://github.com/PlaceholderAPI/PlaceholderAPI/blob/master/wiki/README.md).
          
          It is recommended to [join our Discord Server](https://helpch.at/discord) as you often receive faster response compared to the issue tracker here.
          
          > *This is an automated response created by a GitHub-Action.*
          > *Responding to the bot or mentioning it won't have any effect!*
        action: close
  - name: 'Target: Wiki'
    labeled:
      issue:
        body: |-
          Hello @{{ issue.user.login }},
          
          Thank you for reaching out to us about the wiki.
          We would like to inform you, that you are now able to directly commit your changes to the wiki through a Pull request.
          When doing so, make sure you follow these steps:
          
          - The Pull request targets the [`docs/wiki`](https://github.com/PlaceholderAPI/PlaceholderAPI/tree/docs/wiki) branch of the Repository.
          - You only made changes to the files inside the `wiki` folder.
          - You followed the general Styling Guidelines mentioned in the wiki's [README](https://github.com/PlaceholderAPI/PlaceholderAPI/blob/docs/wiki/wiki/README.md) file.
          
          If you have any questions about submitting a PR for the wiki or have any other questions don't hesitate to ask us about it.
          
          > *This is an automated response created by a GitHub-Action.*
          > *Responding to the bot or mentioning it won't have any effect!*
  - name: 'Type: Not a bug'
    labeled:
      issue:
        body: |-
          The issue you encounter is not considered a bug and rather an intentional behaviour of PlaceholderAPI and/or one of its expansions.
          If you still believe that it is a bug, provide more information and a maintainer of this repository may look at it more closely.
          
          Before providing more info, always make sure to use the latest version of PlaceholderAPI, as the issue you encounter might already be fixed in a newer version.
          Optionally can you also try out [development builds](https://ci.extendedclip.com/job/PlaceholderAPI/) and see if the issue was fixed there.
          
          > *This is an automated response created by a GitHub-Action.*
          > *Responding to the bot or mentioning it won't have any effect!*
        action: close
    unlabeled:
      issue:
        body: |-
          After further investigation is the issue you encounter indeed considered a bug and we will try to fix it as soon as possible.
          
          > *This is an automated response created by a GitHub-Action.*
          > *Responding to the bot or mentioning it won't have any effect!*
        action: open
