site_name: PlaceholderAPI Wiki
site_description: Wiki of the Spigot Plugin PlaceholderAPI.
site_author: PlaceholderAPI Team and Contributors

#site_url: 'https://wiki.placeholderapi.com' # Maybe?

site_url: https://docs.andre601.ch/PlaceholderAPI # Temp until final decision and possible push to upstream

copyright: |-
  &copy; PlaceholderAPI Team and Contributors.<br>
  All content is licensed under <a href="https://github.com/PlaceholderAPI/PlaceholderAPI/blob/master/LICENSE" target="_blank" rel="nofollow">GNU GPL v3.0</a> unless stated otherwise.<br>
  <br>
  <a href="#__consent">Manage Cookies</a>

repo_name: PlaceholderAPI/PlaceholderAPI
repo_url: https://github.com/PlaceholderAPI/PlaceholderAPI

theme:
  name: material
  logo: assets/img/icon.png
  favicon: assets/img/icon.png
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: octicons/sun-24
        name: 'Switch to dark theme'
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: octicons/moon-24
        name: 'Switch to light theme'
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - content.tooltips
    - content.code.copy

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our wiki and whether users find what
      they're searching for. With your consent, you're helping us to make our
      wiki better.
    actions:
      - accept
      - reject
      - manage

nav:
  - index.md
  - commands.md
  - User Guides:
    - users/using-placeholders.md
    - users/placeholder-list.md
    - users/plugins-using-placeholderapi.md
  - Dev Guides:
    - developers/using-placeholderapi.md
    - developers/creating-a-placeholderexpansion.md
    - developers/expansion-cloud.md
  - common-issues.md
  - faq.md
  - Discord: https://discord.gg/helpchat

extra_javascript:
  - assets/js/latest-release.js

extra_css:
  - assets/stylesheets/link-icons.css
  - assets/stylesheets/styling.css

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - meta
  - pymdownx.superfences
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      provider: github
      user: PlaceholderAPI
      repo: PlaceholderAPI
      normalize_issue_symbols: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.blocks.admonition:
      types:
        - note
        - abstract
        - info
        - tip
        - success
        - question
        - warning
        - failure
        - danger
        - bug
        - example
        - quote
  - pymdownx.blocks.details
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.tasklist