name: PlaceholderAPI
main: me.clip.placeholderapi.PlaceholderAPIPlugin
version: ${pom.version}
author: [extended_clip]
description: A placeholder provider
permissions:
    placeholderapi.*:
        description: ability to use all commands
        children:
            placeholderapi.admin: true
    placeholderapi.admin:
        description: ability to use all commands
        children:
            placeholderapi.list: true
            placeholderapi.reload: true
            placeholderapi.parse: true
            placeholderapi.injector.chat.bypass: true
            placeholderapi.injector.signs.bypass: true
            placeholderapi.injector.anvil.bypass: true
    placeholderapi.list:
        description: ability to use the list command
        default: op
    placeholderapi.reload:
        description: ability to use the reload command
        default: op
    placeholderapi.parse:
        description: ability to use parse command
        default: op
commands:
   placeholderapi:
     description: PlaceholderAPI command
     aliases: [clipsplaceholderapi, papi]
