blank_issues_enabled: false
contact_links:
  - name: HelpChat Discord
    url: https://discordapp.com/invite/0utOOIYX82aImw7h
    about: Please join our Discord for faster support.
  - name: Wiki
    url: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki
    about: The Wiki of PlaceholderAPI.
  - name: Hastebin
    url: https://paste.helpch.at
    about: Use our Hastebin-site for sharing errors and configuration files.
  - name: Update Wiki
    url: https://github.com/PlaceholderAPI/PlaceholderAPI/pulls
    about: Please make a Pull request towards the "wiki" folder to update the wiki.
  - name: Questions
    url: https://github.com/PlaceholderAPI/PlaceholderAPI/discussions
    about: If you have any questions, ask them in our Discussions Page.
